config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    authenticated { root to: 'posts#index' }
    unauthenticated { root to: 'devise/sessions#new', as: :root_url }
  end
  resources :users, only: :index

  resources :posts do
    resources :comments
  end

  resources :friend_requests, only: %i[index create destroy]
  resources :friendships, only: %i[create destroy]
  get 'friends', to: 'friendships#index', as: :friends
  resources :likes, only: %i[create destroy]
  resource :profile
  resource :menu, controller: 'menu', only: :show
  scope ':username', constraints: { username: %r{[^/]+} } do
    resources :notifications, only: %i[index create update destroy] do
      patch :read_all, on: :collection
      delete :clear_all_loaded, on: :collection
    end
  end
  get ':username', to: 'users#show', constraints: { username: %r{[^/]+} }, as: :user

  get 'posts/:post_id/comments/minimize',
      to: 'comments#minimize',
      as: :minimize_comments
end

app/models/user.rb
require 'down'
require 'securerandom'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers: %i[facebook]

  attr_writer :login

  has_many :sent_requests,
           class_name: 'FriendRequest',
           foreign_key: :requester_id,
           dependent: :destroy
  has_many :received_requests,
           class_name: 'FriendRequest',
           foreign_key: :requestee_id,
           dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :sent_notifications, foreign_key: 'sender_id', class_name: 'Notification', dependent: :destroy
  has_many :received_notifications, foreign_key: 'receiver_id', class_name: 'Notification', dependent: :destroy
  has_one :profile, dependent: :destroy
  delegate :avatar, to: :profile

  validates :username, length: { maximum: 50 }, uniqueness: true, presence: true
  validates :email, length: { maximum: 50 }

  after_create :create_profile, unless: :omniauth_provider?

  after_create :send_welcome_email

  scope :all_except, ->(user) { where.not(id: user) }

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(
        [
          'lower(username) = :value OR lower(email) = :value',
          { value: login.downcase }
        ]
      ).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def not_friends
    User.all_except(self).to_a.difference(friends.to_a)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = "#{auth.info.name.downcase.gsub(/\s+/, '.')}#{SecureRandom.random_number(10_000)}"
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'])
        user.provider = data['provider']
        user.uid = data['uid']
        profile = user.build_profile(display_name: data['info']['first_name'])
        profile.avatar.attach(
          io: Down.download(data['info']['image']),
          filename: "fb_avatar_#{profile.id}",
          content_type: 'image/jpeg'
        )
      end
    end
  end

  def omniauth_provider?
    provider
  end

  def create_profile(avatar_file = nil, display_name = nil)
    profile = Profile.create!(user: self, display_name:)
    profile.avatar.attach(
      io: (avatar_file || File.open("#{Rails.root}/app/assets/images/head_avatar.jpg")),
      filename: "avatar#{profile.id}#{Time.current.hash}",
      content_type: 'image/jpeg'
    )
  end

  def name
    profile.nil? || profile.display_name.blank? ? username : profile.display_name
  end

  def send_welcome_email
    return unless persisted?

    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    auth = request.env['omniauth.auth']
    @user = User.from_omniauth(auth)
    if @user.persisted?
      @user.create_profile(Down.download(auth.info.image), auth.info.first_name) unless @user.profile

      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = auth.except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def back_to_homepage
    flash[:alert] = 'Please allow access to email address to sign in with Facebook.'
    failure
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all_except(current_user).order(:username)
    @friends_list = current_user.friends
    @not_friends_list = current_user.not_friends
    @sent_requests_users =
      FriendRequest
      .where(requester_id: current_user.id)
      .includes(:requestee)
      .map { |request| request.requestee }
    @received_requests = FriendRequest.where(requestee_id: current_user.id).includes(:requester)
    @received_requests_users = @received_requests.map { |request| request.requester }
    @potential_friends = @sent_requests_users + @received_requests_users
  end

  def show
    if params.key?(:username)
      @user = User.find_by(username: params[:username])
      @profile = Profile.find_by(user_id: @user) || Profile.create(user: @user)
      @posts = Post.where(author: @user).order(created_at: :desc)
    else
      # user not found
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<%# guard clause necessary? %>
<div>
  <% if profile.avatar.attached? && profile.user == current_user %>
    <%= tag.span image_tag(profile.avatar), class: "profile-avatar own", title: "Change your avatar", data: {action: "click->modal#show"} %>
  <% else %>
    <%= tag.span image_tag(profile.avatar), class: "profile-avatar", title: "Avatar" %>
  <% end %>
</div>

app/views/users/_content.html.erb
<div class="users-page-content">
    <h2 class="content-title-container">
      <span class="mdi mdi-account-group"></span>
      All Users
    </h2>
    <ul class="users-list">
      <% users.each do |user| %>
        <li class="user-card-item">
          <%= image_tag user.avatar, class: "profile-pic-icon" %>
          <div class="card-item-details">
            <div class="card-item-middle">
              <%= link_to user.name, user_path(username: user.username) %>
              <%= tag.span class: "mdi mdi-account-multiple" if current_user.friends.include?(user)%>
            </div>
            <% if not_friends_list.include?(user) && potential_friends.exclude?(user) %>
              <div class="card-item-right">
                <%= button_to friend_requests_path, class: "add-friend", form: {style: 'display:inline-block;'}, params: { user: user } do %>
                  <span class="mdi mdi-account-plus"></span>Add Friend
                <% end %>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

app/views/users/_edit_avatar.html.erb
<div data-modal-target="modalcontainer" id="add-image-modal" data-action="mousedown->modal#stopPropagation">
  <div class="modal-content" data-modal-target="modaldialog" data-action="mousedown->modal#stopPropagation">
    <div class="modal-top">
      <h3 class="modal-title">Update profile picture</h3>
      <span class="mdi mdi-close modal" data-action="click->modal#close"></span>
    </div>
    <hr>
    <%= form_with model: profile do |form| %>
      <%= form.hidden_field :id, name: :id, value: profile.id %>
      <div class="modal-middle" data-controller="image-preview">
      <div class="image-preview-window">Preview:
        <div><%= image_tag(profile.avatar, class: "preview-avatar", "data-image-preview-target" => "output") %></div>
      </div>
    <div>
      <%= form.label :avatar, "Change Photo" %>
      <%= form.file_field :avatar, accept: 'image/png,image/jpeg', data: {"image-preview-target" => "input", action: "image-preview#readImage"} %>
    </div>
  </div>
      <hr>
      <div class="modal-footer" data-modal-target="modalFooter">
        <%= form.button "Save" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_edit_cover_photo.html.erb
<div class="edit-cover-photo-container" data-controller="cover-photo">
  <%= button_tag type: "button", class: "add-cover-photo-button", data: {action: "click->cover-photo#toggle"} do %>
    <span class="mdi mdi-camera"></span>
    <%= tag.span "Edit", class: "text" %>
  <% end %>
  <div class="edit-cover-photo-selection" data-cover-photo-target="menu">
    <%= form_with model: profile, data: {turbo: false} do |form| %>
      <%= form.hidden_field :id, name: "id", value: profile.id %>
      <%= form.label 'cover_photo' do %>
        <span class="mdi mdi-upload-outline"></span>Upload Photo
        <%= form.file_field 'cover_photo', accept: 'image/png,image/jpeg', onchange: "this.form.submit()" %>
      <% end %>
    <% end %>
  <% if profile.cover_photo.attached? %>
    <%= button_to profile_path, method: :delete, name: "cover_photo", value: "purge", form: {data: {turbo_confirm: "Are you sure you want to remove your cover photo?"}} do %>
      <span class="mdi mdi-delete-outline"></span>Remove
    <% end %>
  <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="profile-info">
  <%= render partial: "users/avatar", locals: {profile: profile} %>

  <div class="profile-info-details">
    <%= turbo_frame_tag "profile-details" do %>
      
      <%= tag.span profile.display_name, class: "display-name" %>
      <%= tag.span profile.user.username, class: "username" %>
      <%= tag.span profile.bio, class: "bio" %>

      <span class="show-company-container">
        <%= tag.span '', class: "mdi mdi-domain" %>
        <%= tag.span profile.company, class: "company" %>
      </span>
      <span class="show-location-container">
        <%= tag.span '', class: "mdi mdi-map-marker" %>
        <%= tag.span profile.location, class: "location" %>
      </span>
      <span class="show-email-container">
        <%= tag.span '', class: "mdi mdi-email" %>
        <%= tag.span profile.user.email, class: "email" %>
      </span>
      <% if profile.user == current_user %>
        <%= link_to "Edit Profile", edit_profile_path(id: profile.id), class: "edit-profile-button" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= tag.div class: "users-page" do %>
  <%= render "shared/sidebar" %>
  <%= render partial: "content",  locals: {users: @users, received_requests: @received_requests, sent_requests_users: @sent_requests_users, received_requests_users: @received_requests_users, not_friends_list: @not_friends_list, potential_friends: @potential_friends}%>
<% end %>

app/views/users/show.html.erb
<%= tag.div class: "profile", data: { controller: "modal"} do %>
	<div class="cover-photo-container">
		<% if @profile.cover_photo.attached? %>
			<%= image_tag @profile.cover_photo %>
		<% else %>
			<div class="cover-photo-placeholder"></div>
		<% end %>
	</div>

	<%= render "profile", profile: @profile, user: @user %>
	
	<div class="profile-posts">
		<% if @user == current_user %>
			<%= render partial: "users/edit_cover_photo", locals: { profile: @profile } %>
			<%= render "posts/new_post_placeholder" %>
		<% end %>

		<%= turbo_frame_tag "posts" do %>
			<% if @posts.empty? && @user != current_user %>
				<div class="post-container empty">No posts to show.</div>
			<% end %>
			<% @posts.each do |post| %>
				<%= render partial: "posts/post", locals: { post: post, likes: post.likes.includes(:user) }%>
			<% end %>
		<% end %>
	</div>
	<%= render partial: "users/edit_avatar", locals: {profile: @profile} %>
<% end %>