config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    authenticated { root to: 'posts#index' }
    unauthenticated { root to: 'devise/sessions#new', as: :root_url }
  end
  resources :users, only: :index

  resources :posts do
    resources :comments
  end

  resources :friend_requests, only: %i[index create destroy]
  resources :friendships, only: %i[create destroy]
  get 'friends', to: 'friendships#index', as: :friends
  resources :likes, only: %i[create destroy]
  resource :profile
  resource :menu, controller: 'menu', only: :show
  scope ':username', constraints: { username: %r{[^/]+} } do
    resources :notifications, only: %i[index create update destroy] do
      patch :read_all, on: :collection
      delete :clear_all_loaded, on: :collection
    end
  end
  get ':username', to: 'users#show', constraints: { username: %r{[^/]+} }, as: :user

  get 'posts/:post_id/comments/minimize',
      to: 'comments#minimize',
      as: :minimize_comments
end

app/views/shared/_flash.html.erb
<div class="flash", id="flash" data-controller="flash">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %><span class="mdi mdi-close" data-action="click->flash#remove"></span></p>
  <% end %>
  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %><span class="mdi mdi-close" data-action="click->flash#remove"></span></p>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="logo-container">
    <%= link_to "Odinbook", root_path, class: "logo" %>
  </div>

  <div class="header-right" data-controller="menu">
    <%= render partial: "shared/notification", locals: {unread_count: @unread_count, notifications: @notifications} %>
      <div class="profile-pic-icon-container">
        <%= image_tag current_user.avatar, class: "profile-pic-icon", title: "Account", data: {action: "click->menu#toggleMenu"} %>
        <div class="after" data-action="click->menu#toggleMenu"></div>
      </div>
      <div class="account-menu" data-menu-target="menu">
        <%= button_to destroy_user_session_path, method: :delete, class: "logout", data: { turbo: false } do %>
          <span class="mdi mdi-logout"></span>Log Out
        <% end %>
        <%= button_to user_registration_path, data: { turbo: false }, method: :delete, class: "delete-account", onclick: "if (!window.confirm('Are you sure you want to delete your account?')) event.preventDefault()" do %>
          <span class="mdi mdi-account-remove"></span>Delete Account
        <% end %>
      </div>
    <%= link_to menu_path, class: 'menu-link' do %>
      <span class="mdi mdi-menu"></span>
    <% end %>
  </div>
</header>

app/views/shared/_notification.html.erb
<div class="notification" id="notification" data-controller="menu">
  <%= button_to read_all_notifications_path(username: current_user.username), method: :patch, 'data-menu-target' => 'notificationButton', title: "Notifications", params: {ids: notifications.pluck(:id)} do %>
    <span class="mdi mdi-bell"></span>
    <% if unread_count > 0 %>
      <span class="notification-badge" id="notification-badge"><%= unread_count %></span>
    <% end %>
  <% end %>
</div>

app/views/shared/_notification_dropdown.html.erb
<div class="notification-dropdown-container" data-menu-target="notificationMenu">
  <div class="notification-dropdown-header">
    <h3>Notifications</h3>
    <%= button_to clear_all_loaded_notifications_path(username: current_user.username), method: :delete, params: {ids: notifications.pluck(:id)} do %>
      <span class="clear-all">Clear All</span>
    <% end %>
  </div>
  <div class="notifications-list" id="notifications-list">
  <% notifications.each do |notification| %>
    <%= tag.div class: "notifications-list-item", id: dom_id(notification) do %>
      <%= image_tag notification.sender.profile.avatar, width: 45, height: 45, class: "profile-pic-icon" %>
      <p><%= notification.message %></p>
      <%= button_to notification_path(username: current_user.username, id: notification.id), method: :delete, params: { ids: notifications.pluck(:id) } do %>
        <span class="mdi mdi-close"></span>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<%= tag.div class: "friends-page-sidebar" do %>

  <%= link_to friends_path, class: ("active" if current_page?(controller: 'friendships', action: 'index')) do %>
    <div class="icon-container">
      <span class="mdi mdi-account-multiple"></span>
    </div>
    Friends
  <% end %>

  <%= link_to friend_requests_path, class: ("active" if current_page?(controller: 'friend_requests', action: 'index')) do %>
    <div class="icon-container">
      <span class="mdi mdi-account-arrow-right"></span>
    </div>
    Friend Requests
  <% end %>

  <%= link_to users_path, class: ("active" if current_page?(controller: 'users', action: 'index')) do %>
    <div class="icon-container">
      <span class="mdi mdi-account-group"></span>
    </div>
    All Users
  <% end %>
  
  <%= button_to destroy_user_session_path, method: :delete, class: "logout", form: {  data: { turbo: :false } } do %>
    <div class="icon-container"><span class="mdi mdi-logout"></span></div>Log Out
  <% end %>
  
  <%= button_to user_registration_path, data: { turbo: false }, method: :delete, class: "delete-account", onclick: "if (!window.confirm('Are you sure you want to delete your account?')) event.preventDefault()" do %>
    <span class="mdi mdi-account-remove"></span>Delete Account
  <% end %>
<% end %>

app/views/shared/_topnav.html.erb
<nav class="topnav">
    <ul>
      <li>
      <% if current_page?(root_path) %>
        <%= link_to tag.span(class: "mdi mdi-home"), root_path, title: "Home", class: "active" %>
      <% else %>
        <%= link_to tag.span(class: "mdi mdi-home-outline"), root_path, title: "Home" %>
      <% end %>
      </li>
      <li>
      <% if current_page?("/#{current_user.username}") %>
         <%= link_to tag.span(class: "mdi mdi-account"), "/#{current_user.username}", title: "Profile", class: "active" %>
      <% else %>
        <%= link_to tag.span(class: "mdi mdi-account-outline"), "/#{current_user.username}", title: "Profile" %>
      <% end %>
      </li>
      <li>
      <% if current_page?(friends_path) %>
        <%= link_to tag.span(class: "mdi mdi-account-multiple"), friends_path, title: "Friends", class: "active" %>
      <% else %>
        <%= link_to tag.span(class: "mdi mdi-account-multiple-outline"), friends_path, title: "Friends" %>
      <% end %>
      </li>
      <li>
      <% if current_page?(friend_requests_path) %>
        <%= link_to tag.span(class: "mdi mdi-account-arrow-right"), friend_requests_path, title: "Friend Request", class: "active" %>
      <% else %>
        <%= link_to tag.span(class: "mdi mdi-account-arrow-right-outline"), friend_requests_path, title: "Friend Request" %>
      <% end %>  
      </li>
      <li>
      <% if current_page?(users_path) %>
        <%= link_to tag.span(class: "mdi mdi-account-group"), users_path, title: "All Users", class: "active" %>
      <% else %>
        <%= link_to tag.span(class: "mdi mdi-account-group-outline"), users_path, title: "All Users" %>
      <% end %>
      </li>
    </ul>
  </nav>