config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    authenticated { root to: 'posts#index' }
    unauthenticated { root to: 'devise/sessions#new', as: :root_url }
  end
  resources :users, only: :index

  resources :posts do
    resources :comments
  end

  resources :friend_requests, only: %i[index create destroy]
  resources :friendships, only: %i[create destroy]
  get 'friends', to: 'friendships#index', as: :friends
  resources :likes, only: %i[create destroy]
  resource :profile
  resource :menu, controller: 'menu', only: :show
  scope ':username', constraints: { username: %r{[^/]+} } do
    resources :notifications, only: %i[index create update destroy] do
      patch :read_all, on: :collection
      delete :clear_all_loaded, on: :collection
    end
  end
  get ':username', to: 'users#show', constraints: { username: %r{[^/]+} }, as: :user

  get 'posts/:post_id/comments/minimize',
      to: 'comments#minimize',
      as: :minimize_comments
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :requestee,
             class_name: 'User',
             counter_cache: :received_requests_count
  has_one :notification, as: :notifiable

  validates :requester, uniqueness: { scope: :requestee }

  validate :cannot_send_reciprocal_friend_request, :cannot_send_request_to_self

  after_create -> { create_notification(sender: requester, receiver: requestee) }

  def cannot_send_reciprocal_friend_request
    if FriendRequest.find_by(requester: requestee, requestee: requester)
      errors.add(:base, "Please confirm the friend request from #{requestee.name}.")
    end
  end

  def cannot_send_request_to_self
    errors.add(:base, 'Cannot send a friend request to youself.') if requester == requestee
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @received_requests =
      current_user.received_requests.includes(:requester, :requestee)
    @sent_requests =
      current_user.sent_requests.includes(:requester, :requestee)
  end

  def create
    request = current_user.sent_requests.build
    request.requestee = User.find(params[:user])
    if request.save
      redirect_to users_path, notice: 'Friend request sent successfully.'
    else
      redirect_to users_path, alert: 'Oops, something went wrong.'
    end
  end

  def destroy
    request = FriendRequest.find(params[:id])
    request.destroy
    redirect_to friend_requests_path,
                status: :see_other,
                notice: 'Friend request deleted.'
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_content.html.erb
<div class="friend-requests-page-content">

  <div class="content-title-container">
    <span class="mdi mdi-account-arrow-right"></span>
    <h2>Friend Requests</h2>
  </div>

  <div>
    <%= render partial: "received_list", locals: {received_requests: @received_requests} %>
    <%= render partial: "sent_list", locals: {sent_requests: @sent_requests} %>
  </div>
 
</div>

app/views/friend_requests/_received_list.html.erb
<div class="received-requests-container">

  <div class="friend-requests-heading">
    <h3>Received Requests</h3>
    <hr>
  </div>
  
  <% if received_requests.empty? %>
    <p>No requests to show.</p>
  <% else %>
    <ul class="friend-requests-list">
      <% received_requests.each do |request| %>
        <li class="friend-request-card-item">
          <%= image_tag request.requester.avatar, class: "profile-pic-icon" %>
            <div class="friend-request-card-item-details">
              <div class="card-item-middle">
                <%= link_to request.requester.name, user_path(username: request.requester.username) %>
              </div>
              <div class="card-item-right">
                <%= button_to "Confirm", friendships_path, class: "confirm", form: { style: "display: inline-block", data: {turbo: false} }, params: { request_id: request, friend_id: request.requester } %>
                <%= button_to "Delete", friend_request_path(request), class: "delete", method: :delete, form: { style: "display: inline-block", data: {turbo: false} } %>
              </div>
            </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/friend_requests/_sent_list.html.erb
<div class="sent-requests-container">

  <div class="friend-requests-heading">
    <h3>Sent Requests</h3>
    <hr>
  </div>
  
  <% if sent_requests.empty? %>
    <p>No requests to show.</p>
  <% else %>
    <ul class="friend-requests-list">
      <% sent_requests.each do |request| %>
        <li class="friend-request-card-item">
          <%= image_tag request.requestee.avatar, class: "profile-pic-icon" %>
            <div class="friend-request-card-item-details">
              <div class="card-item-middle">
                <%= link_to request.requestee.name, user_path(username: request.requestee.username) %>
              </div>
              <div class="card-item-right">
                <%= button_to "Cancel Request", friend_request_path(request), method: :delete, class: "cancel-request", form: {style: 'display:inline-block;'} %>
              </div>
            </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/friend_requests/index.html.erb
<%= tag.div class: "friend-requests-page" do %>
  <%= render "shared/sidebar" %>
  <%= render "content" %>
<% end %>