config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    authenticated { root to: 'posts#index' }
    unauthenticated { root to: 'devise/sessions#new', as: :root_url }
  end
  resources :users, only: :index

  resources :posts do
    resources :comments
  end

  resources :friend_requests, only: %i[index create destroy]
  resources :friendships, only: %i[create destroy]
  get 'friends', to: 'friendships#index', as: :friends
  resources :likes, only: %i[create destroy]
  resource :profile
  resource :menu, controller: 'menu', only: :show
  scope ':username', constraints: { username: %r{[^/]+} } do
    resources :notifications, only: %i[index create update destroy] do
      patch :read_all, on: :collection
      delete :clear_all_loaded, on: :collection
    end
  end
  get ':username', to: 'users#show', constraints: { username: %r{[^/]+} }, as: :user

  get 'posts/:post_id/comments/minimize',
      to: 'comments#minimize',
      as: :minimize_comments
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  validate :image_format

  belongs_to :author, class_name: 'User'

  private

  def image_format
    return unless image.attached?
    return if image.content_type.in?(%w[image/jpeg image/png])

    image.purge
    errors.add(:avatar, 'Needs to be an image in .jpeg or .png format')
  end
end

app/controllers/posts_controller.rb
require 'down'
require 'news-api'

class PostsController < ApplicationController
  def index
    set_no_cache_headers
    if turbo_frame_request_id == 'new_post_frame'
      render partial: 'posts/new_post_placeholder'
    else
      current_user_posts = current_user.posts.includes(:likes)
      friends_posts =
        current_user
        .friends
        .includes(:posts)
        .flat_map { |friend| friend.posts.includes(:likes) }
      @timeline_posts =
        (current_user_posts + friends_posts)
        .sort_by { |post| post.created_at }
        .reverse
      unless Headline.first && ((Time.current - Headline.first.updated_at) / 1.hour).round < 12
        Headline.destroy_all
        news = News.new(ENV['NEWS_API_KEY'])
        news.get_top_headlines(country: 'jp').each do |headline|
          Headline.create(
            name: headline.name,
            title: headline.title,
            url: headline.url,
            url_to_image: headline.urlToImage,
            published_at: headline.publishedAt
          )
          break if Headline.count >= 3
        end
      end
      @headlines = Headline.all
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params.except(:image_data_url))
    process_image_attachment

    if @post.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'New post created.' }
        format.turbo_stream { flash.now[:notice] = 'New post created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(post_params.except(:image_data_url))
      process_image_attachment

      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Post was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Post was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: 'Post was deleted successfully.' }
      format.turbo_stream { flash.now[:notice] = 'Post was deleted successfully.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :image_url, :image_data_url)
  end

  def process_image_attachment
    image_data_url = params[:post][:image_data_url]
    if image_data_url == 'attached'
      return
    elsif params[:post][:image_data_url].present?
      create_or_update_image_attachment
    elsif params[:post][:image_data_url].empty?
      delete_image_attachment
    end
  end

  def create_or_update_image_attachment
    data_url = params[:post][:image_data_url].split(',')[1]
    @post.image.attach(
      io: StringIO.new(Base64.decode64(data_url)),
      filename: "image#{@post.id}.jpg"
    )
  end

  def delete_image_attachment
    @post.image.purge
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_attach_image.html.erb
<div data-modal-target="modalcontainer" data-image-preview-target="modalContainer" id="add-image-modal">
  <div class="modal-content" data-modal-target="modaldialog">
    <div class="modal-top">
      <h3 class="modal-title">Attach Image</h3>
      <span class="mdi mdi-close modal" data-action="click->modal#close"></span>
    </div>
    <hr>
    <%= form_with model: post do |form| %>
      <div class="modal-middle">
        <div class="modal-selection-container">
          <div class="modal-radio-labels">
            <%= form.radio_button :choose_image, "url", 'data-action' => 'modal#disableFileImage', 'data-modal-target' => 'imageURLRadioButton' %>
            <%= form.label :choose_image_url, 'Image URL' %>
          </div>
          <%= form.text_field :image_url, onkeydown: "return event.keyCode != 13;", 'data-action' => 'modal#clearImagePreviewContainer', 'data-modal-target' => 'imageUrl', disabled: true %>
        </div>
        <div class="modal-selection-container">
          <div class="modal-radio-labels">
            <%= form.radio_button :choose_image, "file", 'data-action' => 'modal#disableImageURL', 'data-modal-target' => 'imageFileRadioButton', 'data-image-preview-target' => 'imageFileRadioButton' %>
            <%= form.label :choose_image_file, 'Select from file' %>
          </div>
          <div class="file-field-row">
            <%= form.label :ximage_file, "Choose File", 'data-modal-target' => 'labelButton' %>
            <%= form.file_field :image_file, accept: 'image/png,image/jpeg', 'data-modal-target' => 'filefrompc', 'data-image-preview-target' => 'filefrompc', 'data-action' => 'change->modal#showCropper', disabled: true %>
          </div>
          <div class="image-preview-container" data-modal-target="imagePreviewContainer" data-image-preview-target="imagePreviewContainer"></div>
        </div>
      </div>
      <hr>
      <div class="modal-footer" data-modal-target="modalFooter" data-image-preview-target="modalFooter">
        <%= form.button "Select Image", 'data-modal-target' => 'submitBtn', 'data-image-preview-target' => 'submitBtn', onClick: "event.preventDefault();" %>
        <%= button_tag "Cancel", name: "cancel", type: "button", data: {action: 'modal#close'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, data: { controller: 'modal image-preview' } do |form| %>
  <%= form.text_area :body, placeholder: "What's on your mind?", required: true %>
  <% post.errors.full_messages_for(:body).each do |message| %>
    <span class="post-error-message"><%= message %></span>
  <% end %>
  <div class="image-preview" data-modal-target="output" data-image-preview-target="output" style=<%= "display:block;" if post.image.attached? || post.image_url.present? %>>
    <div class="overlay">
      <span class="mdi mdi-close" data-action="click->modal#undoImageAttachment"></span>
    </div>
    <% if post.image.attached? %>
      <%= image_tag post.image, class: "post-image", alt: "post image" %>
    <% elsif post.image_url.present? %>
      <%= image_tag post.image_url, class: "post-image", alt: "post image" %>
    <% end %>
  </div>
  <%= form.hidden_field :image_url, 'data-modal-target' => 'hiddenURLField' %>
  <%= form.hidden_field :image_data_url, value: ("attached" if post.image.attached?), 'data-modal-target' => 'hiddenDataURLField', 'data-image-preview-target' => 'hiddenDataURLField' %>
  <div class="new-post-buttons-container">
    <span class="attach-image-link" data-action="click->modal#show" data-modal-target="showModalLink" data-image-preview-target="showModalLink">
      <span class="mdi mdi-image"></span> Attach image
    </span>
    <%= form.submit "Post", 'data-action' => 'click->modal#showPageSpinner' %>
  </div>
  <%= render "attach_image", post: @post %>
<% end %>
  

app/views/posts/_headlines.html.erb
<div class="whats-happening-container">
  <h3>What's happening</h3>
  <div class="headlines-container">
  <% @headlines.each do |headline| %>
    <%= link_to headline.url, class: "headline-item", target: :_blank do %>
      <div>
        <%= tag.span headline.name, class: "name" %>
        <%= tag.span headline.title, class: "title" %>
      </div>
      <%= image_tag headline.url_to_image, onerror: "this.style.display='none'" %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/posts/_like_button.html.erb
<% if likes.none? { |like| like.user == current_user } %>
  <%= button_to likes_path, params: { id: post }, form: { id: "like-button-#{post.id}" } do %>
    <span class="mdi mdi-thumb-up-outline"></span>
    <span class="button-text">Like</span>
  <% end %>
<% else %>
  <%= button_to like_path(id: likes.where(user_id: current_user.id).first), method: :delete, params: { post_id: post.id, like_id: likes.where(user_id: current_user.id).first.id }, form: { id: "like-button-liked-#{post.id}" } do %>
    <span class="mdi mdi-thumb-up"></span>
    <span class="button-text">Like</span>
  <% end %>
<% end %>

app/views/posts/_like_count_line.html.erb
<p class="like-count-line">
  <b style="color: black"><%= like_count %></b>
  <%= like_count.between?(0,1) ? "Like" : "Likes" %>
</p>

app/views/posts/_new_post_placeholder.html.erb
<%= turbo_frame_tag "new_post_frame" do %>
  <div class="post-container placeholder">
    <%= image_tag current_user.avatar, class: "profile-pic-icon" %>
    <a href="posts/new" class="post-text-placeholder">What's on your mind<span class="name">, <%= current_user.name %></span>?</a>
  </div>
<% end %>

app/views/posts/_options.html.erb
<div class="ellipsis-container" data-controller="menu">
  <span class="mdi mdi-dots-horizontal" data-action="click->menu#toggleMenu"></span>
  <div class="ellipsis-dropdown-container" data-menu-target="menu">
    <%= link_to edit_post_path(post), class: "item edit-post-link" do %>
      <span class="mdi mdi-lead-pencil"></span>Edit Post
    <% end %>
    <%= button_to post_path(post), method: :delete, class: "item" do %>
      <span class="mdi mdi-trash-can-outline"></span>Delete Post
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post, class: "turbo-frame-post" do %>
  <%= tag.div class: "post-container published", data: {controller: "comments", comments_target: "publishedPost"}, id: dom_id(post) do %>

    <div class="post-author-container">
      <%= link_to user_path(username: post.author.username), class: 'post-avatar-link', data: {turbo: false} do %>
        <%= image_tag post.author.avatar, class: "profile-pic-icon" %>
      <% end %>
      <div class="user-info">
        <%= link_to user_path(username: post.author.username), class: 'user-info-name-link', data: {turbo: false} do %>
          <p class="user-info-name"><%= post.author.name %></p>
        <% end %>
        <p class="user-info-date"><%= post.created_at.in_time_zone('Tokyo').strftime("%l:%M %p - %b %d, %Y") %></p>
      </div>
      <%= render partial: "posts/options", locals: {post: post} if post.author == current_user %>
    </div>

    <p class="post-body-text"><%= post.body %></p>

    <% if post.image_url.present? %>
      <%= link_to image_tag(post.image_url, class: 'post-image'), post.image_url, data: {turbo_action: 'advance'} %>
    <% elsif post.image.attached? %>
      <%= link_to image_tag(post.image, class: 'post-image'), post.image, data: { turbo_action: 'advance' } %>
    <% end %>

    <hr>
    
    <%= tag.div class: "counts-container" do %>
      <%= turbo_frame_tag "post-likes-#{post.id}" do %>
        <%= render "posts/like_count_line", like_count: post.likes.count %>
      <% end %>
      <% if post.comments.present? %>
        <% if post.comments.size == 1 %>
          <%= tag.span "1 Comment", class: "comment-count-line", data: {postid: post.id, 'comments-target' => 'commentCount'} %>
        <% else %>
          <%= tag.span "#{post.comments.size} Comments", class: "comment-count-line", data: {postid: post.id, 'comments-target' => 'commentCount'} %>
        <% end %>
      <% end %>
    <% end %>

    <hr>

    <div class="post-buttons">
      <%= render partial: "posts/like_button", locals: {post: post, likes: likes} %>
      <%= render partial: "posts/comment_button", locals: {post: post} %>
    </div>
  <% end %>
<% end %>

app/views/posts/_sidebar.html.erb
  <div class="main-homepage-sidebar">

    <%= link_to user_path(username: current_user.username), class: "sidebar-item" do %>
      <%= image_tag current_user.avatar, class: "profile-pic-icon homepage-sidebar" %>
      <%= tag.span current_user.name, class: "item-label" %>
    <% end %>

    <%= link_to friends_path, class: "sidebar-item" do %>
      <span class="mdi mdi-account-multiple"></span>
      <span class="item-label">Friends</span>
    <% end  %>

    <%= link_to users_path, class: "sidebar-item" do %>
      <span class="mdi mdi-account-group"></span>
      <span class="item-label">All Users</span>
    <% end %>

  </div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.remove "page-overlay" %>
<%= turbo_stream.prepend "posts", partial: "post", locals: { post: @post, likes: @post.likes.includes(:user) } %>
<%= turbo_stream.replace "new_post_frame", partial: "new_post_placeholder" %>
<%= turbo_stream.prepend "root", partial: "shared/flash" %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag @post do %>
  <div class="post-container edit">
    <div class="post-author-container">
      <%= image_tag current_user.avatar, class: "profile-pic-icon" %>
      <div class="user-info">
        <%= current_user.name %>
      </div>
      <%= link_to root_path, class: "close-link" do %>
        <span class="mdi mdi-close"></span>
      <% end %>
    </div>
      <%= render 'form', post: @post %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="main-homepage">

  <%= render "sidebar" %>

  <div class="main-homepage-center">
    <%= render "posts/new_post_placeholder" %>
    
    <%= turbo_frame_tag "posts" do %>
      <% @timeline_posts.each do |post| %>
        <%= render partial: "post", locals: { post: post, likes: post.likes.includes(:user) }%>
      <% end %>
    <% end %>
  </div>

  <div class="main-homepage-right">
    <%= render partial: "posts/headlines", locals: {headlines: @headlines} %>
  </div>

</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "new_post_frame" do %>
  <div class="post-container new">
    <div class="post-author-container">
      <%= image_tag current_user.avatar, class: "profile-pic-icon" %>
      <div class="user-info">
        <%= current_user.name %>
      </div>
      <%= link_to root_path, class: "close-link" do %>
        <span class="mdi mdi-close"></span>
      <% end %>
    </div>
      <%= render 'form', post: @post %>
  </div>
<% end %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.remove "page-overlay" %>
<%= turbo_stream.replace @post, partial: "post", locals: { post: @post, likes: @post.likes.includes(:user) } %>
<%= turbo_stream.prepend "root", partial: "shared/flash" %>